# A headless governing service
apiVersion: v1
kind: Service
metadata:
  name: es-sts-hs
  labels:
    app: es-cluster
spec:
  clusterIP: None
  selector:
    app: es-cluster
  ports:
  - name: transport
    port: 9300
